function ACC = metrics_acc_update(ACC, t, method, Fo, Ft, lonVec, latVec, isLand, isOcean)
%METRICS_ACC_UPDATE Update accumulator with one month of data.
    rec = struct( ...
        't', t, ...
        'method', method, ...
        'Fo', Fo, ...
        'Ft', Ft, ...
        'lonVec', lonVec, ...
        'latVec', latVec, ...
        'isLand', isLand, ...
        'isOcean', isOcean);
    ACC = metrics_acc_update_struct(ACC, rec);
end
