function plotCfg = get_plot_cfg(cfg)
%GET_PLOT_CFG Build plotting configuration with defaults.

    plotCfg = struct( ...
        'quicklook', false, ...
        'metrics_ts', true, ...
        'metrics_maps', true, ...
        'stack_mean', true, ...
        'stack_trend_amp', true, ...
        'basin_overlay', true, ...
        'auto_caxis_mean', true, ...
        'auto_caxis_prc', [2 98], ...
        'caxis', struct('ewh', [-30 30], 'trend', [-5 5], 'amp', [-15 15]), ...
        'cmap', struct('ewh', 'jet', 'trend', 'redblue', 'amp', 'jet'));

    if isfield(cfg, 'plot')
        plotCfg = merge_struct(get_plot_cfg_defaults(), cfg.plot);
    end

    if isfield(cfg, 'plot') && isfield(cfg.plot, 'caxis')
        if ~isfield(plotCfg.caxis, 'ewh'); plotCfg.caxis.ewh = [-30 30]; end
        if ~isfield(plotCfg.caxis, 'trend'); plotCfg.caxis.trend = [-5 5]; end
        if ~isfield(plotCfg.caxis, 'amp'); plotCfg.caxis.amp = [-15 15]; end
    end

    if isfield(cfg, 'plot') && isfield(cfg.plot, 'auto_caxis_mean')
        plotCfg.auto_caxis_mean = cfg.plot.auto_caxis_mean;
    end

    if isfield(cfg, 'plot') && isfield(cfg.plot, 'auto_caxis_prc')
        plotCfg.auto_caxis_prc = cfg.plot.auto_caxis_prc;
    end

    if ~isfield(plotCfg, 'cmap') || isempty(plotCfg.cmap)
        plotCfg.cmap = struct('ewh', 'jet', 'trend', 'redblue', 'amp', 'jet');
    else
        if ~isfield(plotCfg.cmap, 'ewh'); plotCfg.cmap.ewh = 'jet'; end
        if ~isfield(plotCfg.cmap, 'trend'); plotCfg.cmap.trend = 'redblue'; end
        if ~isfield(plotCfg.cmap, 'amp'); plotCfg.cmap.amp = 'jet'; end
    end
end

function defaults = get_plot_cfg_defaults()
    defaults = struct( ...
        'quicklook', false, ...
        'metrics_ts', true, ...
        'metrics_maps', true, ...
        'stack_mean', true, ...
        'stack_trend_amp', true, ...
        'basin_overlay', true, ...
        'auto_caxis_mean', true, ...
        'auto_caxis_prc', [2 98], ...
        'caxis', struct('ewh', [-30 30], 'trend', [-5 5], 'amp', [-15 15]), ...
        'cmap', struct('ewh', 'jet', 'trend', 'redblue', 'amp', 'jet'));
end

function out = merge_struct(base, override)
    out = base;
    if isempty(override); return; end
    f = fieldnames(override);
    for i = 1:numel(f)
        out.(f{i}) = override.(f{i});
    end
end
