"""Compatibility shim for canonical ui.plotting.projections."""

from grace_pipeline.ui.plotting.projections import (
    apply_proj_scale,
    get_conic_parallels,
    get_proj_center,
    infer_plot_lon_mode,
    normalize_lon_for_plot,
    normalize_lon_input,
    parse_float,
    proj_aeqd,
    proj_albers,
    proj_eckert4,
    proj_equalearth,
    proj_lambert_conformal,
    proj_mercator,
    proj_miller,
    proj_mollweide,
    proj_orthographic,
    proj_robinson,
    proj_sinusoidal,
    proj_stereographic,
    proj_winkeltripel,
    region_is_custom,
    scale_projection,
    split_plot_lon_segments,
    wrap_delta_lon,
)

__all__ = [
    "infer_plot_lon_mode",
    "normalize_lon_for_plot",
    "split_plot_lon_segments",
    "normalize_lon_input",
    "region_is_custom",
    "parse_float",
    "wrap_delta_lon",
    "get_proj_center",
    "get_conic_parallels",
    "scale_projection",
    "apply_proj_scale",
    "proj_robinson",
    "proj_mollweide",
    "proj_mercator",
    "proj_miller",
    "proj_sinusoidal",
    "proj_equalearth",
    "proj_winkeltripel",
    "proj_eckert4",
    "proj_orthographic",
    "proj_aeqd",
    "proj_stereographic",
    "proj_lambert_conformal",
    "proj_albers",
]
